---
- name: Fix Bar Mitzvah
  hosts: barmitzvah_vulnerable:&windows:!exceptions
  tasks:
    - name: Disable RC4 40-128
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128
        name: Enabled
        data: 0
        type: dword
        state: present
    - name: Disable RC4 56-128
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128
        name: Enabled
        data: 0
        type: dword
        state: present
    - name: Disable RC4 128-128
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128
        name: Enabled
        data: 0
        type: dword
        state: present
