---
- name: Fix CredSSP
  hosts: credssp_vulnerable:!exceptions 
  tasks:
    - name: Set Encyption Oracle to 0
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters
        name: AllowEncryptionOracle
        data: 0
        type: dword
        state: present
