---
- name: Fix Logjam
  hosts: logjam_vulnerable:&windows:!exceptions
  tasks:
    - name: Set Diffie-Hellman minimum client key length to 2048 bits
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman
        name: ClientMinKeyBitLength
        data: 0x00000800
        type: dword
        state: present
    - name: Set Diffie-Hellman minimum server key length to 2048 bits
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman
        name: ServerMinKeyBitLength
        data: 0x00000800
        type: dword
        state: present
