---
- name: Disable SMBv1 for Windows 7
  hosts: winsmbv1_vulnerable:&win7
  tasks:
    - name: Disable SMBv1 for Server
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: SMB1
        data: 0
        type: dword
        state: present
    - name: Disable SMBv1 for Client
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: SMB1
        data: 0
        type: dword
        state: present
    - name: Disable SMBv1 for Client
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10
        name: Start
        data: 4
        type: dword
        state: present
