---
- name: Enable SMB Signing
  hosts: smbsigning_vulnerable:&windows 
  tasks:
    - name: Set Require Signature for Workstation
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: RequireSecuritySignature
        data: 1
        type: dword
        state: present
    - name: Set Require Signature for Server
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: RequireSecuritySignature
        data: 1
        type: dword
        state: present
