---
- name: Enable modern TLS on Windows 10
  hosts: win10
  tasks:
    - name: Disable TLSv1.1 Client
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
        name: DisabledByDefault
        data: 1
        type: dword
        state: present
    - name: Disable TLSv1.1 Server
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
        name: DisabledByDefault
        data: 1
        type: dword
        state: present