---
- name: Enable modern TLS on Windows 7
  hosts: win7:!exceptions 
  tasks:
    - name: Disable TLSv1.1 Client
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
        name: DisabledByDefault
        data: 1
        type: dword
        state: present
    - name: Disable TLSv1.1 Server
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
        name: DisabledByDefault
        data: 1
        type: dword
        state: present
    - name: Enable TLSv1.2 Client
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
        name: DisabledByDefault
        data: 0
        type: dword
        state: present
    - name: Enable TLSv1.2 Server
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
        name: DisabledByDefault
        data: 0
        type: dword
        state: present
    - name: Enable WinHTTP modern TLS
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings
        name: WinHttp
        data: 0x00000A00
        type: dword
        state: present
